/**
 * Loot table data for the Vagabond Loot Generator.
 * Source: Vagabond RPG core book loot tables + community spreadsheet.
 */

// ── Level Formulas ──────────────────────────────────────────────────────────
export const LEVEL_FORMULAS = {
  2:  { treasure: "d4",      armor: "d4",      weapon: "d6",       alchemy: "2d12" },
  3:  { treasure: "d6",      armor: "d6",      weapon: "d8",       alchemy: "2d12+8" },
  4:  { treasure: "d6",      armor: "d8",      weapon: "d10",      alchemy: "2d12+16" },
  5:  { treasure: "d4+d6",   armor: "d4+d8",   weapon: "d6+d10",   alchemy: "2d12+d12+16" },
  6:  { treasure: "d6+d6",   armor: "d6+d8",   weapon: "d10+d10",  alchemy: "2d12+d12+24" },
  7:  { treasure: "d4+2d6",  armor: "d8+d8",   weapon: "d6+2d10",  alchemy: "2d12+2d12+24" },
  8:  { treasure: "d6+2d6",  armor: "d4+2d8",  weapon: "d10+2d10", alchemy: "2d12+2d12+32" },
  9:  { treasure: "d4+3d6",  armor: "d6+2d8",  weapon: "d6+3d10",  alchemy: "2d12+2d12+40" },
  10: { treasure: "d6+3d6",  armor: "d8+2d8",  weapon: "d10+3d10", alchemy: "2d12+2d12+48" },
};

// ── Treasure Chain ──────────────────────────────────────────────────────────
export const TREASURE = {
  1:  "Trade Goods (d6)",
  2:  "Art (d8), worth 20g",
  3:  "Jewelry (d12), worth 10g",
  4:  "1d8 Uncommon Gems (0-Slot, 5g each)",
  5:  "Coins: 5d10 gold",
  6:  "Relic Item (d6)",
  7:  "Trade Goods (d6+6)",
  8:  "Art (d8), worth 100g",
  9:  "Jewelry (d12), worth 50g",
  10: "1d4 Rare Gems (0-Slot, 50g each)",
  11: "Coins: (2d12)\u00d710 gold",
  12: "Relic Item (d6+6)",
  13: "Trade Goods (d6+12)",
  14: "Art (d8), worth 500g",
  15: "Jewelry (d12), worth 250g",
  16: "1d10 Very Rare Gems (0-Slot, 100g each)",
  17: "Coins: (2d6)\u00d7100 gold",
  18: "Relic Item (d6+12)",
  19: "Trade Goods (d6+18)",
  20: "Art (d8), worth 2500g",
  21: "Jewelry (d12), worth 1000g",
  22: "2d20 Very Rare Gems (0-Slot, 100g each)",
  23: "Coins: (d8)\u00d7500 gold",
  24: "Relic Item (d6+18)",
};

export const TRADE_GOODS = {
  1:  "1d100 Spice, Common",
  2:  "1d20 Spice, Exotic",
  3:  "1d12 Spice, Rare",
  4:  "1d20 Ingots, Copper",
  5:  "1d10 Ingots, Silver",
  6:  "1 Ingot, Gold",
  7:  "1d100 Spice, Exotic",
  8:  "1d20 Spice, Rare",
  9:  "1d20 Ingots, Silver",
  10: "1d100 Ingots, Silver",
  11: "1d4 Ingots, Gold",
  12: "1d8 Ingots, Gold",
  13: "1d100 Spice, Rare",
  14: "1d100 Ingots, Silver",
  15: "1d6 Ingots, Gold",
  16: "1d8 Ingots, Gold",
  17: "1d12 Ingots, Gold",
  18: "1d20 Ingots, Gold",
  19: "1d12 Ingots, Gold",
  20: "1d20 Ingots, Gold",
  21: "2d20 Ingots, Gold",
  22: "1d100 Ingots, Gold",
  23: "1 Ingot, Platinum (5000g)",
  24: "1d4 Ingots, Platinum (5000g)",
};

export const ART = {
  1: "Tapestry (3-Slot)",
  2: "Painting, moderate (1-Slot)",
  3: "Painting, sizable (2-Slot)",
  4: "Figurine / Bust (1-Slot)",
  5: "Statuette (2-Slot)",
  6: "Pottery, moderate (1-Slot)",
  7: "Pottery, sizable (2-Slot)",
  8: "Historic artifact (1-Slot)",
};

export const JEWELRY = {
  1:  "Amulet / Necklace",
  2:  "Belt buckle, decorative",
  3:  "Barrette",
  4:  "Bracelet",
  5:  "Circlet",
  6:  "Earring",
  7:  "Locket",
  8:  "Monocle",
  9:  "Pendant",
  10: "Ring",
  11: "Spectacles",
  12: "\u2192Clothing",
};

export const CLOTHING = {
  1:  "Belt",
  2:  "Boots",
  3:  "Cape",
  4:  "Cloak",
  5:  "Cowl",
  6:  "Doublet",
  7:  "Dress",
  8:  "Frock",
  9:  "Girdle",
  10: "Gloves",
  11: "Leggings",
  12: "Mantle",
  13: "Pants",
  14: "Scarf",
  15: "Shirt",
  16: "Shoes",
  17: "Skirt",
  18: "Tunic",
  19: "Vest",
  20: "Vestments",
};

export const RELIC = {
  1:  "Armor of Vulnerability -1",
  2:  "Weapon of Weakness -1",
  3:  "Bag of Devouring",
  4:  "Pixie Dust",
  5:  "Golden Needle",
  6:  "Broom of Flying",
  7:  "Armor of Vulnerability -2",
  8:  "Weapon of Weakness -2",
  9:  "Decanter of Endless Water",
  10: "Cloak of Displacement",
  11: "Cube of Force",
  12: "Bag of Holding (5-Slot)",
  13: "Armor of Vulnerability -2",
  14: "Weapon of Weakness -3",
  15: "Phoenix Down",
  16: "Orb of Many Energies",
  17: "Magistaff, Common",
  18: "Bag of Holding (5-Slot)",
  19: "Armor of Vulnerability -3",
  20: "Weapon of Weakness -3",
  21: "Bag of Holding (10-Slot)",
  22: "Magistaff, Rare",
  23: "Necklace of Adaptation",
  24: "Magistaff, Legendary",
};

// ── Armor Chain ─────────────────────────────────────────────────────────────
/** @type {Array<[number, number, string]>} [low, high, name] */
export const ARMOR_BASE = [
  [1,  2,  "Clothing Set"],
  [3,  4,  "Robes"],
  [5,  5,  "Light Armor, Padded"],
  [6,  7,  "Light Armor, Leather"],
  [8,  8,  "Light Armor, Hide"],
  [9,  10, "Medium Armor, Chain"],
  [11, 12, "Medium Armor, Scale"],
  [13, 14, "Heavy Armor, Splint"],
  [15, 16, "Heavy Armor, Plate"],
  [17, 19, "Accessory"],
  [20, 20, "Scroll, Enchantment"],
];

export const ARMOR_POWER = {
  1:  "Material Table (d6)",
  2:  "Resistance (d3)",
  3:  "Protection, Niche (last fought)",
  4:  "Armor +1",
  5:  "Movement (d6)",
  6:  "Protection +1",
  7:  "Utility (d8)",
  8:  "Reroll as d8, twice (reroll 8s)",
  9:  "Senses (d4)",
  10: "Resistance (d8, reroll 1-3s)",
  11: "Protection, Specific",
  12: "Armor +2",
  13: "Movement (d8+6)",
  14: "Protection +2",
  15: "Utility (d6+8)",
  16: "Reroll as d8+8, twice (reroll 8s)",
  17: "Senses (d4+4)",
  18: "Utility (d4+13)",
  19: "Protection, General (d8)",
  20: "Armor +3",
  21: "Fabled, Benediction",
  22: "Protection +3",
  23: "Reroll d8, d8+8, d6+16",
  24: "Reroll d6+16 twice",
};

export const ARMOR_MATERIAL = {
  1: "Adamant", 2: "Adamant",
  3: "Mythral", 4: "Mythral",
  5: "Orichalcum", 6: "Orichalcum",
  7: "Mundane", 8: "Mundane", 9: "Mundane",
  10: "Mundane", 11: "Mundane", 12: "Mundane",
};

export const ARMOR_RESISTANCE = {
  1: "Bravery", 2: "Clarity", 3: "Repulsing",
  4: "Acid Resist", 5: "Cold Resist", 6: "Fire Resist",
  7: "Poison Resist", 8: "Shock Resist",
};

export const ARMOR_UTILITY = {
  1:  "After-Image 1",
  2:  "Darkness 1",
  3:  "Moonlight 1",
  4:  "Infinite",
  5:  "Ambassador",
  6:  "Darkness 2",
  7:  "Moonlight 2",
  8:  "Radiant 1",
  9:  "After-Image 2",
  10: "Aqua Lung",
  11: "Darkness 3",
  12: "Invisibility 1",
  13: "Moonlight 3",
  14: "Radiant 2",
  15: "Warning",
  16: "Radiant 3",
  17: "Invisibility 2",
};

// ── Weapon Chain ────────────────────────────────────────────────────────────
export const WEAPONS_LIST = [
  "Arbalest", "Battleaxe", "Buckler", "Caestus", "Crossbow", "Crossbow, light",
  "Dagger", "Flail", "Gauntlet", "Greataxe", "Greatclub", "Greatshield",
  "Greatsword", "Handaxe", "Handgun", "Javelin", "Katar", "Lance",
  "Light hammer", "Longbow", "Longsword", "Lucerne", "Mace", "Morningstar",
  "Pike", "Poleblade", "Rifle", "Shotgun", "Shotgun, sawed-off", "Sling",
  "Spear", "Staff", "Standard shield", "Shortbow", "Shortsword", "Warhammer",
  "Whip, chain", "Whip, leather", "Scroll, Enchantment", "Spell Book",
  "Trinket \u2014 Arcane", "Trinket \u2014 Arcane",
  "Trinket \u2014 Divine", "Trinket \u2014 Divine",
  "Trinket \u2014 Occult", "Trinket \u2014 Occult",
  "Trinket \u2014 Primal", "Trinket \u2014 Primal",
];

export const WEAPON_POWER = {
  1:  "Material (d4)",
  2:  "Weapon +1",
  3:  "Resistance (d4, reroll 4s)",
  4:  "Bane, Niche (last fought)",
  5:  "Movement (d6)",
  6:  "Utility (d4)",
  7:  "Utility (d6)",
  8:  "Strike 1",
  9:  "Reroll as d8, twice",
  10: "Add d10 to this roll",
  11: "Ace",
  12: "Weapon +2",
  13: "Senses (d4)",
  14: "Bane, Specific",
  15: "Movement (d6+d8)",
  16: "Utility (d6+3)",
  17: "Utility (d6+6)",
  18: "Strike 2",
  19: "Reroll as d8+10, twice",
  20: "Add d10 to this roll",
  21: "Fabled, Blasting",
  22: "Weapon +3",
  23: "Senses (2d4)",
  24: "Bane, General (d8)",
  25: "Movement (d8+6)",
  26: "Utility (d6+9)",
  27: "Utility (d6+12)",
  28: "Strike 3",
  29: "Reroll as d8+20, twice",
  30: "Add d10 to this roll",
  31: "Fabled, Precision",
  32: "Fabled, Vicious",
  33: "Senses (d4+4)",
  34: "Fabled, Benediction",
  35: "Fabled, Soul-Eater",
  36: "Utility (d6+18)",
  37: "Utility (d6+21)",
  38: "Fabled, Vorpal",
  39: "Reroll d8, d8+9, d8+19, d8+29",
  40: "Reroll d8+29 twice",
};

export const WEAPON_MATERIAL = {
  1: "Silver", 2: "Cold Iron", 3: "Adamant", 4: "Mythral",
  5: "Mundane", 6: "Mundane", 7: "Mundane", 8: "Mundane",
};

export const WEAPON_RESISTANCE = {
  1: "Bravery", 2: "Clarity", 3: "Repulsing",
};

export const WEAPON_UTILITY = {
  1:  "After-Image 1",
  2:  "Darkness 1",
  3:  "Moonlight 1",
  4:  "Infinite",
  5:  "Lifesteal 1",
  6:  "Loyalty",
  7:  "Ambassador",
  8:  "Darkness 2",
  9:  "Moonlight 2",
  10: "Manasteal 1",
  11: "Radiant 1",
  12: "After-Image 2",
  13: "Burning 1",
  14: "Aqua Lung",
  15: "Darkness 3",
  16: "Invisibility 1",
  17: "Moonlight 3",
  18: "Radiant 2",
  19: "Warning",
  20: "Lifesteal 2",
  21: "Burning 2",
  22: "Manasteal 2",
  23: "Radiant 3",
  24: "Invisibility 2",
  25: "Lifesteal 3",
  26: "Manasteal 3",
  27: "Burning 3",
};

// ── Alchemy ─────────────────────────────────────────────────────────────────
export const ALCHEMY = {
  2:  "Poison, Basic",
  3:  "Acid, Basic",
  4:  "Acid, Defoliator",
  5:  "Acid, Oxidizing",
  6:  "Adhesive",
  7:  "Alchemist's Fire",
  8:  "Alkahest",
  9:  "Antitoxin",
  10: "Clearbreath",
  11: "Darksight powder",
  12: "Frigid azote",
  13: "Holy water",
  14: "Ice skin",
  15: "Insect repellent",
  16: "Levin shell",
  17: "Longbreath",
  18: "Oil, Annointing",
  19: "Oil, Bladefire",
  20: "Shriek Paste",
  21: "Spell Scroll (0 Mana)",
  22: "Spell Scroll (1 Mana)",
  23: "Spell Scroll (2 Mana)",
  24: "Spell Scroll (3 Mana)",
  25: "Sunrod",
  26: "Tanglefoot bag",
  27: "Thunderstone",
  28: "Torch, Tendertwig",
  29: "Dwarfblind stone",
  30: "Gravebane",
  31: "Instant rope",
  32: "Poison, Deadly Nightshade",
  33: "Poison, Truth Serum",
  34: "Torch, Frigidflame",
  35: "Torch, Repel Beast",
  36: "Candle, Calming",
  37: "Candle, Restful",
  38: "Potion, Anger I",
  39: "Potion, Healing I",
  40: "Potion, Speed I",
  41: "Splash catalyst",
  42: "Acid, Green Slime",
  43: "Instant wall",
  44: "Oil, Crone's Ire",
  45: "Spell Scroll (4 Mana)",
  46: "Spell Scroll (5 Mana)",
  47: "Spell Scroll (6 Mana)",
  48: "Spell Scroll (7 Mana)",
  49: "Oil, Ghostflame",
  50: "Oil, Wyrmwound",
  51: "Oil, Vicious",
  52: "Potion, Regeneration I",
  53: "Torch, Sentry",
  54: "Homunculus soup",
  55: "Potion, Mana I",
  56: "Potion, Speed II",
  57: "Potion, Regeneration II",
  58: "Scroll, Protection from Evil",
  59: "Scroll, Protection from Good",
  60: "Potion, Mana II",
  61: "Potion, Invulnerability I",
  62: "Potion, Anger II",
  63: "Potion, Control Beast",
  64: "Potion, Diminution",
  65: "Potion, Healing II",
  66: "Potion, Resistance (Cold)",
  67: "Potion, Resistance (Fire)",
  68: "Potion, Resistance (Shock)",
  69: "Spell Scroll (8 Mana)",
  70: "Spell Scroll (9 Mana)",
  71: "Spell Scroll (10 Mana)",
  72: "Spell Scroll (11 Mana)",
  73: "Potion, Speed III",
  74: "Potion, Levitation",
  75: "Potion, Clairaudience",
  76: "Potion, Invisibility",
  77: "Potion, Mana III",
  78: "Potion, Polymorph",
  79: "Potion, Regeneration III",
  80: "Potion, Clairvoyance",
  81: "Potion, Growth",
  82: "Potion, Anger III",
  83: "Potion, Control Person",
  84: "Potion, ESP",
  85: "Potion, Freedom",
  86: "Potion, Gaseous Form",
  87: "Potion, Giant Strength",
  88: "Potion, Healing III",
  89: "Potion, Invulnerability II",
  90: "Potion, Control Monster",
  91: "Potion, Flying",
  92: "Spell Scroll (12 Mana)",
  93: "Spell Scroll (13 Mana)",
  94: "Spell Scroll (14 Mana)",
  95: "Spell Scroll (15 Mana)",
  96: "Potion, Invulnerability III",
};

// ── Shared Sub-Tables ───────────────────────────────────────────────────────
export const SENSES = {
  1: "Nightvision", 2: "Echolocation", 3: "Tremors", 4: "Detection",
  5: "Sense Life", 6: "Sense Valuables", 7: "Telepathy", 8: "True-Seeing",
};

export const MOVEMENT = {
  1:  "Swiftness 1",
  2:  "Climbing",
  3:  "Jumping 1",
  4:  "Levitation",
  5:  "Waterwalk",
  6:  "Webwalk",
  7:  "Displacement",
  8:  "Swiftness 2",
  9:  "Blinking",
  10: "Clinging",
  11: "Jumping 2",
  12: "Flying",
  13: "Swiftness 3",
};

export const CREATURE_GENERAL = {
  1: "Artificial", 2: "Beast", 3: "Cryptids", 4: "Fae",
  5: "Humanlike", 6: "Outers", 7: "Primordials", 8: "Undead",
};

export const CREATURE_SPECIFIC = {
  1:  "Artificial, Architecture",
  2:  "Artificial, Item",
  3:  "Artificial, Golem",
  4:  "Artificial, War Machine",
  5:  "Beast, Aquatic",
  6:  "Beast, Avian",
  7:  "Beast, Insectoid",
  8:  "Beast, Mammalian",
  9:  "Beast, Reptilian",
  10: "Cryptid (Beast)",
  11: "Cryptid, Chimeric",
  12: "Cryptid, Colossals",
  13: "Cryptid, Giants",
  14: "Cryptid, Humanlike",
  15: "Cryptid, Mimickers",
  16: "Cryptid, Reptilian",
  17: "Cryptid (Shapechanger)",
  18: "Cryptid (Wyrm)",
  19: "Fae, Aquatic",
  20: "Fae (Beast)",
  21: "Fae (Divine)",
  22: "Fae, Humanlike",
  23: "Fae (Shapechanger)",
  24: "Fae, Spirit",
  25: "Fae (Wyrm)",
  26: "Outer (Beyonder)",
  27: "Outer (Divine)",
  28: "Outer (Hellspawn)",
  29: "Outer, Other",
  30: "Primordial (Djinn)",
  31: "Primordial, Elemental",
  32: "Primordial (Plant)",
  33: "Primordial (Shapechanger)",
  34: "Primordial (Slime)",
  35: "Undead (Beast)",
  36: "Undead (Shapechanger)",
  37: "Undead, Skeletal",
  38: "Undead, Spirit",
  39: "Undead, Zombie",
  40: "Undead, Other",
};
